### ISSUE TITLE
Any plan to update docker image?

### ISSUE THREAD

**Issue by edwardzjl** [juju-solutions/jujubox#35]
The official image on dockerhub labeled latest contains juju 2.7.6

Current juju version is 2.9.x

Is there any plan to update the docker image?

**Comment by pengale** [comment]
Hello, @edwardzjl! jujubox is deprecated at this point.

For building charms, the focus has moved to using charmcraft (https://juju.is/docs/sdk/setting-up-charmcraft) to build charms using the Operator Framework (https://github.com/canonical/operator).

Juju itself is typically delivered as a snap, though it is also available as a standalone Go binary (https://launchpad.net/juju/+download).

Everything is lightweight enough, that it didn't make sense to maintain the docker image w/ Juju.

If you want to isolate juju from your host system more than is possible with the classic snap, you can also run it in an lxd container, or a lightweight vm.

**Comment by edwardzjl** [comment]
Ok the go binary solution fits me well. Thank you, closing this.
