### ISSUE TITLE
Break from upstream?

### ISSUE THREAD

**Issue by mbruzek** [juju-solutions/jujubox#8]
This repository was created by someone who is no longer on the team. We should break the upstream fork.

**Comment by lazypower** [comment]
i'm not entirely certain this is possible... I can reach out to GitHub support and see if they can break the upstream link, but i do believe this has destructive implications.

I'll follow up here when I know more

**Comment by kwmonroe** [comment]
I'm pretty sure @mbruzek did this a few weeks ago.  Looks like juju-solutions/jujubox is no longer a fork of any other repo.

**Comment by mbruzek** [comment]
Yes I broke it from upstream earlier. I would like to take some time to clean up the master branch of this project so devel and master are not too diverged.
